### ISSUE TITLE
create_SURPI_data.sh stumbles on pigz

### ISSUE THREAD

**Issue by dnieuw** [chiulab/surpi#18]
I didn't have pigz installed in my session, so the reference download script crashed. Please add pigz as a requirement to the install script or something.

**Comment by sfederman** [comment]
Hmmm - pigz should be installed by the SURPI_setup.sh script (line 44). Did this fail for you?

**Comment by dnieuw** [comment]
I see, must have been a problem on our side then!
Thanks for the reply.
