### ISSUE TITLE
can surpi working on amplicon data?

### ISSUE THREAD

**Issue by ylzheng** [chiulab/surpi#23]
can surpi working on amplicon data for viral, bacterial detection? 
Thanks!

**Comment by cychiu98** [comment]
Hi  short answer  yes.  We have run it successfully with amplicon data.
-Charles

From:  ylzheng notifications@github.com
Reply-To:  chiulab/surpi
<reply+001313e156324798011870a799a81e5f82457d256867d92e92cf0000000112b90a0b9
2a169ce07a16b1f@reply.github.com>
Date:  Thursday, January 21, 2016 at 1:05 PM
To:  chiulab/surpi surpi@noreply.github.com
Subject:  [surpi] can surpi working on amplicon data? (#23)

can surpi working on amplicon data for viral, bacterial detection?
Thanks!


Reply to this email directly or view it on GitHub
https://github.com/chiulab/surpi/issues/23 .

**Comment by ylzheng** [comment]
@cychiu98, Got it! Thank you!
